#!/usr/bin/env bash

## Here is an interesting spacebar https://github.com/cmacrae/spacebar
## Status bar config taken from https://github.com/FrankLA0203/Dotfiles/blob/master/.config/yabai/yabairc
## Still need to get it to work
## yabai -m config status_bar                   on
## yabai -m config status_bar_text_font         "Helvetica Neue:Regualar:12.0"
## yabai -m config status_bar_icon_font         "FuraMono Nerd Font:Regular:14.0"
## yabai -m config status_bar_background_color  0xff101010
## yabai -m config status_bar_foreground_color  0xfff0f0f0
## yabai -m config status_bar_space_icon_strip     I II III IV V VI VII
## yabai -m config status_bar_power_icon_strip   
## yabai -m config status_bar_space_icon        
## yabai -m config status_bar_clock_icon        

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Variables =============================

gaps_top="3"
gaps_bottom="4"
gaps_left="4"
gaps_right="4"
gaps_inner="4"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"
# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
# yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
